### PR TITLE
clear and dropdown icon builders

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi! Thanks for your work.

I added some more functionality.

Currently in `IconButton` expands widget a lot in case of `UnderlineInputBorder` - https://tppr.me/TlMM1
You can compare how two fields looks like with the same decoration.

I added `clearButtonBuilder` and `dropdownButtonBuilder` to have an ability to override the buttons completely. 
And `suffixIcons` to add an ability to manage the where the icons are placed. Here how it looks now(with `suffixIcons: true`) - https://tppr.me/lnVzZ

### CODE REVIEW

**Comment by vasilich6107** [comment]
It is also allows to make more elegant dropdowns
https://tppr.me/WUokd

**Comment by vasilich6107** [comment]
Hi, @salim-lachdhaf 
Could you review my PR?

**Comment by salim-lachdhaf** [comment]
hi, nice thought,
i have two note :
1- `suffixIcons` i prefer to remove it (already have `showClearButton` and i added in dev branch `showDropdownButton`). because i'm sure a lot of users will be confused ...

2- why passing the callback as parameter, however i think containing the `clearButtonBuilder` or the other inside a `GestureDetector` will be better, think if a user want to override the button but just a widget not an icon or a button ... like image

**Comment by vasilich6107** [comment]
> And suffixIcons to add an ability to manage the where the icons are placed i don't see that

At [this line](https://github.com/salim-lachdhaf/searchable_dropdown/pull/93/files#diff-8905c8a5d0a1f4f37a23ac082cf564a7a34799a608ad86628f7eb3e6fe750d56R296) depending on the flag value the `clear` and `dropdown` buttons are displayed 

> why passing the callback as parameter, however i think containing the clearButtonBuilder or the other inside a GestureDetector will be better

Ok, I'll update my PR to wrap builders in `GestureDetector`

**Comment by vasilich6107** [comment]
> Ok, I'll update my PR to wrap builders in GestureDetector

I have another idea. Passign callback through the builder we have a possibility to add some additional logic.
For example - using `clearButtonBuilder` we can add additional logic to buttons - https://tppr.me/4CdNf

**Comment by salim-lachdhaf** [comment]
> > And suffixIcons to add an ability to manage the where the icons are placed i don't see that
> 
> At [this line](https://github.com/salim-lachdhaf/searchable_dropdown/pull/93/files#diff-8905c8a5d0a1f4f37a23ac082cf564a7a34799a608ad86628f7eb3e6fe750d56R296) depending on the flag value the `clear` and `dropdown` buttons are displayed
> 

yes it is managing the the visibility not where it is place (position).
> > why passing the callback as parameter, however i think containing the clearButtonBuilder or the other inside a GestureDetector will be better
> 
> Ok, I'll update my PR to wrap builders in `GestureDetector`

yes, you have reason and i thought about that, but think what if  it is overrided by simple widget like image , text .... that has no action , (uses the default action behind)

**Comment by vasilich6107** [comment]
> yes it is managing the the visibility not where it is place (position).
Not exactly. Let me give you more information.
In case of `suffixIcons: true` it displays them [here](https://github.com/salim-lachdhaf/searchable_dropdown/pull/93/files#diff-8905c8a5d0a1f4f37a23ac082cf564a7a34799a608ad86628f7eb3e6fe750d56R296)

In case of `suffixIcons: false` it displays them [here](https://github.com/salim-lachdhaf/searchable_dropdown/pull/93/files#diff-8905c8a5d0a1f4f37a23ac082cf564a7a34799a608ad86628f7eb3e6fe750d56R251)

> yes, you have reason and i thought about that
In case of passing the callback we have more flexibility. If your final decision will be `GestureDetector` I will update the PR.

**Comment by salim-lachdhaf** [comment]
nice for the suffix, just maybe i will renale it to `showAsSuffixIcons`.

for the second, consider me as a regular developper, and i want to replace the clear button by a png picture.
do i have to implement the clear action by my self ! by adding a GestureDetector... to handle the action , which meant to be a default action ? this how the developper will react. i'm thinking in another solution that combine between your solution and my point of view, maybe by adding onBefore change or clear and onAfter change callbacks, and the confirmation dialog for example will be called in onBefore (boolean , if true call onAfter)...

**Comment by vasilich6107** [comment]
> nice for the suffix, just maybe i will rename it to `showAsSuffixIcons`

Renamed.

>  i'm thinking in another solution that combine between your solution and my point of view

Could you add more information about your solution when you are ready?

**Review by salim-lachdhaf — COMMENTED** [review]
my idea is to change this function `_handleOnChangeSelectedItem` here https://github.com/salim-lachdhaf/searchable_dropdown/blob/eff3fde4a58f25603014316dad096e56acfea130/lib/dropdown_search.dart#L431

we gonna add a new parameter to the plugin named: 

```
bool onBeforeChanged()
```
the idea is :
```
if(onBeforeChange){
   change value
   widget?.onChanged(selectedItem);
}
```

draft example:

 ```
void _handleOnChangeSelectedItem(T selectedItem) {
    if(widget.onBeforeChanged == true /*handle false and null*/){
          _selectedItemNotifier.value = selectedItem;
           if (widget.onChanged != null) widget.onChanged(selectedItem);
     }
    _handleFocus(false);
  }

```

so for example if the user want to show a confirmation dialog he can do it in `onBefore`, and depend in user response we preceed the data changing.

if you want to implement this part either in your PR, or i will add it from my side in my devs.

**Comment by vasilich6107** [comment]
I got your point. Let me try to implement.

**Comment by vasilich6107** [comment]
Reverted revert of gesture detector
added `onBeforeChange` callback
add example with alert

**Review by salim-lachdhaf — COMMENTED** [review]
is it possible to declare just `bool` not a `Future<bool>`
and replace `onBeforeChange: (a, b) {}` with `onBeforeChange: (a, b) async{}`

same as `onTap` logic on buttons ... ?

**Comment by vasilich6107** [comment]
Unfortunately no.
Async functions return futures.
https://tppr.me/fHiMh

**Comment by vasilich6107** [comment]
Hi @salim-lachdhaf 
I resolved conflicts which occurred after two previous PR's
Can we continue with this PR?

**Review by salim-lachdhaf — APPROVED** [review]

**Pull request merged**
