### PR TITLE
add favorites section on top of list

### PR DESCRIPTION
**Pull request by nizarhdt**
When it come with large data, it's good to have favorites item or frequently chosen item at top of list. It will make end-user faster for choosing item.
Here is example:
Screenshot_20210315-134721

### CODE REVIEW

**Review by salim-lachdhaf — COMMENTED** [review]
.very nice and useful feature, thank you.

`typedef Widget FavoritesChips<T>(T item);`
`typedef List<T> FavoritesData<T>(List<T> item);`
rename them to :

`typedef Widget FavoriteItemsBuilder<T>(BuildContext context, T item);`
`typedef List<T> FavoriteItems<T>(List<T> item);`

and samething to other variables (use word item, items. like favoriteListBuilder, favoriteItems,  showFavoriteItems, ....)

why are adding an item (lenght +1) and working on index 0 ? why just simple add the fovorite widget after the search widget.
add a widget called `_buildFavoriteItems(snapshot.data),` put it outside the listBuilder (it should not be scrollable vertically, should be always visible).
i don't see the default widget for the favorite item (what if the user did not pass the `favoriteItemBuilder` ?)

again nice idea ;)

**Comment by nizarhdt** [comment]
Hi bro,
thanks for feedback.

I just updated the code, now the FavoriteItems is located at bottom of search field and its not scroll like before.
But, i need to make the stream listener to be broadcast.

You can review the code again, Thank You.

**Review by salim-lachdhaf — APPROVED** [review]
Hi , nice work ;)

for manage item as string use this (prevent duplication code and multi same functionning in multi places to keep it simple to mantain...)
```
///function that return the String value of an object
  String _selectedItemAsString(T? data) {
    if (data == null) {
      return "";
    } else if (widget.itemAsString != null) {
      return widget.itemAsString!(data);
    } else {
      return data.toString();
    }
  }
```

**Comment by nizarhdt** [comment]
Hi, just updated the code.

**Comment by salim-lachdhaf** [comment]
could you resolve the conflict please

**Comment by nizarhdt** [comment]
done bro.

**Pull request merged**
