### PR TITLE
popup safe area

### PR DESCRIPTION
**Pull request by vasilich6107**
Fix for #94 

BottomeSheet
- before https://tppr.me/rIw23
- after https://tppr.me/FNkbo

Menu
- before https://tppr.me/gOir3
- after https://tppr.me/1XV5q

### CODE REVIEW

**Comment by salim-lachdhaf** [comment]
is this solve this case : 

bottomSheet with height 700 (top safeArea), after clicking on searchBox (keyboard popup...) ?

**Comment by AsadSaleh** [comment]
Awesome. Many thanks brother.

**Comment by vasilich6107** [comment]
@salim-lachdhaf let me check

**Comment by salim-lachdhaf** [comment]
yes it's a `bottomSheet` issue and we can also pass the context of the parent widget to the plugin and used it to set the padding for `safeArea,` but i don't see it a clean solution.

your solution is more clean, and gives the user the possibility to choose which safeArea he want to use.

after the last solution, i see a possible optimisation, what if we revert all modifications exept `popupSafeArea` class and parameter, and add a `Material` as child (if it works) or a parent of the `_selectDialog` widget ?

**Comment by vasilich6107** [comment]
I'll check

**Comment by vasilich6107** [comment]
I'm currently busy on my work.
May be I'll try to try on the next week

**Pull request merged**
