### PR TITLE
Fixing WidgetsBinding callback implementation which triggered warning on any project...

### PR DESCRIPTION
**Pull request by GaspardMerten**

### CODE REVIEW

**Comment by GaspardMerten** [comment]
@vasilich6107, is it acceptable to move the constraints on Dart from 2.12 to 2.15?

**Comment by vasilich6107** [comment]
@GaspardMerten @salim-lachdhaf 
If you are going to bump to 2.15 and introduce major version update - do not forget to remove deprecated properties

**Comment by GaspardMerten** [comment]
Hello @vasilich6107, I just pushed a commit containing all fixes concerning deprecation and unused imports!

**Comment by GaspardMerten** [comment]
@salim-lachdhaf, Could it be possible to merge this PR ?

**Comment by salim-lachdhaf** [comment]
1 - the instance is nullable, you could not remove `!` or `?` `static WidgetsBinding? get instance => _instance;`
2 -changing dart version will never impact Flutter widgets (except null safety), only Flutter version could cause a problem like yours.

**Comment by GaspardMerten** [comment]
Hello @salim-lachdhaf,

Changing the dart version is required for the new Flutter version!

Since now a few months the widgets binding instance is now non-nullable.

 `static WidgetsBinding get instance => BindingBase.checkInstance(_instance);`

Thus the code in your package throws a warning because a pointless check is made. 

This is what my PR attempts to fix.

Could you please re-open this PR at the least based on this information?

**Pull request closed without merging**
