### PR TITLE
scrollbar

### PR DESCRIPTION
**Pull request by vasilich6107**

### CODE REVIEW

**Review by salim-lachdhaf — COMMENTED** [review]
you have reverted your changes for the scrollbar

**Comment by vasilich6107** [comment]
hmmm, let me double check

**Comment by vasilich6107** [comment]
fixed

**Comment by vasilich6107** [comment]
Hi @salim-lachdhaf 
I fixed the PR
Could we merge it?

**Comment by ashish-andev** [comment]
Hi @salim-lachdhaf 
why when we can expect for scrollbar feature to be release?

**Comment by salim-lachdhaf** [comment]
the new release will be in this weekend

**Pull request merged**
