### PR TITLE
Added property to customize DropdownButton Splash Radius

### PR DESCRIPTION
**Pull request by jiurchuk**
Add possibility to customize the Splash Radius of the Dropdown Button and the Clear Button.

By adding this feature, you can make the radius splash the size you like so it can fit inside the container.

## Dropdown Button
|  Default Size |   Custom Size (20)|
| ------------ | ------------ |
|image|image|

## Clear Button
|  Default Size |   Custom Size (20)|
| ------------ | ------------ |
|image|image|

### CODE REVIEW

**Comment by vasilich6107** [comment]
@jiurchuk we have `dropdownButtonBuilder` and `clearButtonBuilder` for this purposes.
The initial implementation with `IconButton` gives the minimum working conditions.

For all other customizations you can use corresponding builders.

**Comment by vasilich6107** [comment]
The `IconButton` itself has a tonn more props.
In case if we follow current PR strategy we will bloat the props list with `2xtonn` props to be able to specify each `IconButton` prop. Corresponding builders solve this issue in elegant way and gives you much more flexibility

**Comment by jiurchuk** [comment]
> @jiurchuk we have `dropdownButtonBuilder` and `clearButtonBuilder` for this purposes.
> The initial implementation with `IconButton` gives the minimum working conditions.
> 
> For all other customizations you can use corresponding builders.

@vasilich6107 the issue is that if you use a `dropdownButtonBuilder` and inside it you use an `IconButton` then you **must** implement the `onPressed` method. If you implement it (and you must, otherwise Flutter won't compile), then the default tap operation of the Search Dropdown widget won't run (because you are providing another implementation).

So I think that the solution is to provide this Splash Radius via parameter (as seen in this PR) or otherwise you have to make public the `dropdownButtonPressed`/`clearButtonPressed ` methods so we can invoke them from outside.

**Comment by vasilich6107** [comment]
@jiurchuk @salim-lachdhaf 
This is one of the reasons why my initial builder design was
`builder: (onPressed) {}` which will be able to cover this issue.

`IconButton` has this many not passed props

```
    this.iconSize = 24.0,
    this.visualDensity,
    this.padding = const EdgeInsets.all(8.0),
    this.alignment = Alignment.center,
    this.color,
    this.focusColor,
    this.hoverColor,
    this.highlightColor,
    this.splashColor,
    this.disabledColor,
    this.mouseCursor = SystemMouseCursors.click,
    this.focusNode,
    this.autofocus = false,
    this.tooltip,
    this.enableFeedback = true,
    this.constraints,
```

Are we going to pass them all some day?(multiplied by 2 cause we have two of them)

**Pull request merged**
