### PR TITLE
null safety bugfix

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi @salim-lachdhaf 
I added some fixes to the null safety.

After initial migration the package was barely usable due to runtime errors.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '(String) => bool' is not a subtype of type '((String?) => bool)?'
```

I noticed this errors while migrating my package to null safety.

I also migrated `example` to null safety and made it runnable.
Allowed `http` traffic for Android to make requests work while running `example` on emulator

I prepared CHANGELOG and bumped pubspec version.
I hope you'll merge and release new version soon

### CODE REVIEW

**Review by salim-lachdhaf — COMMENTED** [review]
which version of flutter are you using ? beacause that's weired , it's works fine le pluging ...

**Comment by vasilich6107** [comment]
Hi.
I use `flutter 2.0.2`, with sdk `2.12`

Let me give you an example why it couldn't work. This bug for example shines when you'll try to use `popupItemDisabled` prop.

This is [typedef](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L23)
`typedef bool DropdownSearchPopupItemEnabled<T>(T item);` - the item defined as non nullable type

Let's move down - `T` for `DropdownSearch` is also [defined](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L38) as non nullable 

Going deeper - `T` for prop is also defined as non nullable [here](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L156)

On line [479](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L479) we pass `widget.popupItemDisabled` to `itemDisabled` of `SelectDialog`

The aha is a little bit upper - https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L458

`T?` for `SelectDialog` defined as nullable so the same function inside `SelectDialog` will get `T?` as generic [type](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/src/selectDialog.dart#L25)

So due to the incorrect migration we are getting here https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L479

`widget.popupItemDisabled` types as `(String) => bool`
and
`itemDisabled` as `(String?) => bool`

I do not know why static analysis does not handle this.
When you remove `?` [here](https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L244) you'll see all the issues in analyzer.

**Comment by vasilich6107** [comment]
The issue described above is valid for 7 functions - https://tppr.me/envba

itemAsString
filterFn
itemBuilder
compareFn
itemDisabled
favoriteItems
favoriteItemBuilder

**Comment by vasilich6107** [comment]
@salim-lachdhaf I would like to ask you if we can release this into pub.dev

**Comment by salim-lachdhaf** [comment]
i have to validate the fix of safeArea first to release them together

**Pull request merged**
