### PR TITLE
make confirm button title editable in multi select

### PR DESCRIPTION
**Pull request by AbdullahGaber**
you can now edit confirm button title is multi select drop down

### CODE REVIEW

**Comment by salim-lachdhaf** [comment]
we prefer keep attribute grouped like `popProps` ...  to make thing easier to understand to the users and prevent a non readable and handble code

**Comment by JavanFeng** [comment]
> you can use `validationWidgetBuilder` to full customize the ok button.

Hi,I use validationWidgetBuilder to customize the ok button for multilingual, but found not work well, I cannot invoke  `onValidate` to handle selectedItem（SelectionWidget seems not exposed)


Is there any way to solve it ? or is possible pass `onValidate` through  validationWidgetBuilder;

**Comment by salim-lachdhaf** [comment]
could you paste an example for your case

**Comment by JavanFeng** [comment]
here's my case, I just want to change the button'title ,maybe change to `finish`, but I dont know how  to hanle the  onpress action. for getting the origial action,I try `ctx.findRootAncestorStateOfType`,but it cannot get `DropdownSearchState `,it  doesnt work :(
```
import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(
      home: Scaffold(
        body: ExsampleDomain(),
      ),
    ));

class ExsampleDomain extends StatelessWidget {
  const ExsampleDomain({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: DropdownSearch<String>.multiSelection(
        popupProps: PopupPropsMultiSelection.menu(
          validationWidgetBuilder: (ctx, items) => Align(
            alignment: Alignment.centerRight,
            child: ElevatedButton(
              onPressed: () {
                DropdownSearchState<String>? state = ctx
                    .findRootAncestorStateOfType<DropdownSearchState<String>>();
                state?.changeSelectedItems(
                    items); // it doesnt work,state is null
                Navigator.pop(ctx);
              },
              // child: Text(LocaleKeys.ok.tr()),
              child: const Text('finish'),
            ),
          ),
        ),
        dropdownDecoratorProps: const DropDownDecoratorProps(
          dropdownSearchDecoration: InputDecoration(
            hintText: 'select the item',
            border: InputBorder.none,
          ),
        ),
        items: const ["1", "2", "3", '4'],
        onChanged: print,
      ),
    );
  }
}
```

**Comment by JavanFeng** [comment]
> could you paste an example for your case
I pasted the exsample under #534,

**Comment by JavanFeng** [comment]
> could you paste an example for your case

I pasted the exsample under #534

**Comment by naeem-shah** [comment]
I'm experiencing a similar issue. I'm trying to display a full-width button that reflects the number of selected languages. However, after dismissing the bottom sheet, the dropdown fails to display the most recently selected languages.

**Comment by JavanFeng** [comment]
> I'm experiencing a similar issue. I'm trying to display a full-width button that reflects the number of selected languages. However, after dismissing the bottom sheet, the dropdown fails to display the most recently selected languages.

it seems not same to mine. I just forget to use GlobalKey to get the State I want. in your case,it seems about state keeping,dismissing the bottom sheet casuse the whole widget to refresh.

**Comment by hschk** [comment]
@JavanFeng Can you post a working solution with the GlobalKey? Unfortunately I can't get it working... 
Where do you define the GlobalKey and to which Widget are you assigning it? I tried assigning it to the DropdownSearch, but I still can't get the DropdownSearchState.

**Comment by JavanFeng** [comment]
> DropdownSearch

I just define the GlobalKey in the same page,just like this:
```
final GlobalKey<DropdownSearchState> _linkTypeKey = GlobalKey();

Container(
              padding: EdgeInsets.symmetric(vertical: Insets.m),
              child: DropdownSearch<String>.multiSelection(
                key: _linkTypeKey,  // this is globalkey
                ....)

// then get state

_linkTypeKey.currentState?.changeSelectedItems(items);
```

**Comment by hschk** [comment]
Thank you very much, I got it working now :)

**Pull request closed without merging**
