### PR TITLE
Async Items Pagination

### PR DESCRIPTION
**Pull request by acdwisu**

### CODE REVIEW

**Comment by JVasconsueloM** [comment]
@acdwisu 
Issue 1#: Allow disabled or blocked infinite scrolling based on the last page found.
Issue 2#: When you paginate some records and later focus the searchbar, it calls the async function with the first page as a parameter before I start typing.

**Comment by acdwisu** [comment]
@JVasconsueloM 
Thanks for checking this.

For Issue 1, i provide parameter endOfPageErrorIndication of AsyncItemsPaginatedParam property. 
```
///would be tested when exception occured on <code>fn</code> calls and check whether
///the exception is end of page indication or not.
///by default, when fn return empty list, it will mark as end of page
final bool Function(Object)? endOfPageErrorIndication;
```
have you try this parameter?

For Issue #2, i will try to check it at later time.

**Comment by JVasconsueloM** [comment]
@acdwisu I appreciate you taking the time to respond to me.

Yes, but it didn't work for me because it always fired the next pagination and my backend threw an error (400) because the page didn't exist (which is fine), so the best solution in my case is to have a parameter to "block" the next pagination until a search query changed('cause I always know what's the last page).

Issue 2 is caused by the searchfieldcontroller listener. It can be avoided by simply ignoring the initial event. (Because the first load is made in initstate, the focus event fired is not required to call the request function, and it works as expected after that.)

**Comment by mazab99** [comment]
are you added it in MultiSeclection or just on single 
if in MultiSeclection can you share the last file @JVasconsueloM

**Comment by Carlitus77** [comment]
When this feature will be ready?
Thanks for your work!

**Comment by JVasconsueloM** [comment]
@mazab99 I added it only for single selection and personalized only what I needed but if it helps. (sorry if file names dont match with @acdwisu's integration)


```dart
...
class SearchableDropdownModalWidgetState extends State<SearchableDropdownModalWidget> {
  ...
  bool _blockInfinityScroll = false;
  bool isFirstFocus = true;
  int _currentPage = 1;

  Timer? _debounce;

  void searchBoxControllerListener() {
    if (isFirstFocus) { // <--- first change to avoid it calls the async function with the first page before typing
      isFirstFocus = false;
    } else {
      if (_debounce?.isActive ?? false) _debounce?.cancel();
      _debounce = Timer(
        const Duration(milliseconds: 700),
        () {
          manageItemsByFilter(isFirstLoad: true);
        },
      );
    }
  }

  @override
  void initState() {
    super.initState();
    dataProvider = DataProvider(
      apiUrl: widget.apiUrl,
      apiParams: widget.apiParams,
    );
    selectedItemNotifier.value = widget.defaultSelectedItem;

    searchBoxController.addListener(searchBoxControllerListener);
    scrollController.addListener(scrollListener);

    Future.delayed(
      Duration.zero,
      () => manageItemsByFilter(isFirstLoad: true), // <--- changed
    );
  }

  void scrollListener() {
    if (scrollController.position.atEdge &&
        scrollController.position.pixels != 0 &&
        !_blockInfinityScroll) { // <-- block infinite scroll
      manageItemsByFilter(isFirstLoad: false);
    }
  }

  ...
  @override
  Widget build(BuildContext context) {
    return Container(
      constraints: const BoxConstraints(maxHeight: 500),
      child: ValueListenableBuilder(
        valueListenable: selectedItemNotifier,
        builder: (ctx, value, widget) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              SearchableDropdownSearchWidget(searchBoxController: searchBoxController),
              Flexible(
                fit: FlexFit.tight,
                child: Stack(
                  children: <Widget>[
                    SearchableDropdownListWidget(
                      scrollController: scrollController,
                      loadingNotifier: loadingNotifier,
                      items: itemsStream,
                      onItemSelected: handleSelectedItem,
                    ),
                    SearchableDropdownLoadingWidget(loadingNotifier: loadingNotifier)
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );
  }

  void closePopup() => Navigator.pop(context);

  Future<void> manageItemsByFilter({bool isFirstLoad = false}) async {
    loadingNotifier.value = true;

    if (isFirstLoad) {
      itemsCached = [];
      _blockInfinityScroll = false;
      _currentPage = 1;
    }

    await fetchData();

    loadingNotifier.value = false;
  }

  void addDataToStream(List<SearchableDropdownItem> data) {
    if (itemsStream.isClosed) return;
    itemsCached.addAll(data);
    itemsStream.add(itemsCached);
  }

  void _addErrorToStream(Object error, [StackTrace? stackTrace]) {
    if (itemsStream.isClosed) return;
    itemsStream.addError(error, stackTrace);
  }

  void handleSelectedItem(SearchableDropdownItem newSelectedItem) {
    closePopup();
    if (widget.onChanged != null) widget.onChanged!(newSelectedItem);
  }

  Future<void> fetchData() async {
    loadingNotifier.value = true;

    try {
      SearchableDropdownResponse response = await dataProvider.fetchData(
        page: _currentPage,
        query: searchBoxController.text,
      );

      if (response.results.isNotEmpty) {
        addDataToStream(response.results);
        _currentPage++;
        _blockInfinityScroll = (itemsCached.length >= response.count);  // <--  logic was adapted to my own case directly
      }
    } catch (e) {
      _addErrorToStream(e);
    } finally {
      loadingNotifier.value = false;
    }
  }
}
```

**Comment by salim-lachdhaf** [comment]
Thank you for the PR.
The `infiniteScroll` is new feature implemented in the next version v6.0.0-pre that will be released in the next days with much easier way and no complixity.

Stay tuned ;)

**Pull request closed without merging**
