### PR TITLE
Move elevation to props, add offset and menu directions to props

### PR DESCRIPTION
**Pull request by mykhailoKomarNiX**
Hey, 

I've added some changes that allow me to set other elevation value and offset of the menu dropdown pop-up.

Also, direction property was added. It allows you to manage in which direction opening the menu dropdown pop-up, the feature is very useful if dropdown is the last element on the screen

Could you please add the changes to the library?

Thanks

### CODE REVIEW

**Comment by salim-lachdhaf** [comment]
if the dropdownSearch is the last element and there is no space down, the popup Menu will be automatically on top (MenuDirection up) without any extra code, what do you think ?

**Comment by mykhailoKomarNiX** [comment]
No, you need to specify the property "direction" withe the value "MenuDirection.UP"

**Comment by salim-lachdhaf** [comment]
what i meant that this behavior is already exist without adding any extra code (the current merge request)

**Comment by danjenson** [comment]
Can we still move `elevation` to the widget props?

**Comment by mykhailoKomarNiX** [comment]
@salim-lachdhaf I have left only changes that are related to elevation, could you approve and merge them?

**Comment by salim-lachdhaf** [comment]
you forget to add elevation for the dialog.

**Pull request closed without merging**
